# Generated by Django 5.1.7 on 2025-03-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rack')),
            ],
        ),
    ]
